nexus docker hosted repos added

diff --git a/Jenkinsfile-dev b/Jenkinsfile-dev
--- a/Jenkinsfile-dev
+++ b/Jenkinsfile-dev
@@ -64,34 +64,34 @@ pipeline
             }
         }
 
-        // stage('Push Docker Image to Nexus') 
-        // {
-        //     steps {
-        //           withCredentials([usernamePassword(
-        //           credentialsId: 'nexus-npm-cred',   // ensure this is Nexus creds
-        //           usernameVariable: 'USER',
-        //           passwordVariable: 'PASS'
-        //           )]) {
-        //             sh '''
-        //               set -e
+        stage('Push Docker Image to Nexus') 
+        {
+            steps {
+                  withCredentials([usernamePassword(
+                  credentialsId: 'nexus-npm-cred',   // ensure this is Nexus creds
+                  usernameVariable: 'USER',
+                  passwordVariable: 'PASS'
+                  )]) {
+                    sh '''
+                      set -e
 
-        //                   NEXUS_URL="http://65.2.6.0/repository/docker-hosted/"
+                          NEXUS_URL="http://65.2.6.0/repository/docker-hosted/"
 
-        //                   echo "Verifying local image exists..."
-        //                   docker images | grep "${IMAGE_NAME}" || { echo "Image not found"; exit 1; }
+                          echo "Verifying local image exists..."
+                          docker images | grep "${IMAGE_NAME}" || { echo "Image not found"; exit 1; }
 
-        //                   echo "Tagging image for Nexus..."
-        //                   docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG}
+                          echo "Tagging image for Nexus..."
+                          docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG}
 
-        //                   echo "Logging into Nexus..."
-        //                   echo "$PASS" | docker login ${NEXUS_URL} -u "$USER" --password-stdin
+                          echo "Logging into Nexus..."
+                          echo "$PASS" | docker login ${NEXUS_URL} -u "$USER" --password-stdin
 
-        //                   echo "Pushing image..."
-        //                   docker push ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG}
-        //                '''
-        //            }   
-        //     }
-        // }
+                          echo "Pushing image..."
+                          docker push ${NEXUS_URL}/${IMAGE_NAME}:${IMAGE_TAG}
+                       '''
+                   }   
+            }
+        }
 
 
     }
